### ISSUE TITLE
multidimensional parameters raises AttributeError

### ISSUE THREAD

**Issue by notwa** [CMA-ES/pycma#39]
passing a numpy.ndarray with more than one dimension raises the following error:

```
Traceback (most recent call last):
  File "cma_bug.py", line 10, in <module>
    res = cma.fmin(objective, params, 1.0)
  File "[snip]\cma\evolution_strategy.py", line 3885, in fmin
    es = CMAEvolutionStrategy(x0, sigma_factor * sigma0, opts)
  File "[snip]\cma\evolution_strategy.py", line 1324, in __init__
    self._set_x0(x0)  # manage weird shapes, set self.x0
  File "[snip]\cma\evolution_strategy.py", line 1620, in _set_x0
    if self.opts.eval('verbose') >= 0:
AttributeError: 'CMAEvolutionStrategy' object has no attribute 'opts'
```

I can see from the source that this isn't supported anyway, but it fails to reach the code that raises the more informative error.

_PS. this package is amazing, thank you for your hard work!_

**Comment by nikohansen** [comment]
Thanks for the report! This will be fixed with the next push.
